-- Insert Players into the player table.
-- INSERT INTO `player`(`pNumber`, `firstName`, `lastName`, `age`, `team`, `positionGroup`, `positon`)

INSERT INTO `player`(`pNumber`, `firstName`, `lastName`, `age`, `team`, `positionGroup`, `positon`) VALUES
('5', 'Tyrod', 'Taylor', '27', (SELECT teamID FROM teams WHERE mascot = 'Bills'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Offense'), (SELECT positionID FROM positions WHERE position = 'QB')),
('12', 'Aaron', 'Rodgers', '33', (SELECT teamID FROM teams WHERE mascot = 'Packers'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Offense'), (SELECT positionID FROM positions WHERE position = 'QB')),
('3', 'Jameis', 'Winston', '21', (SELECT teamID FROM teams WHERE mascot = 'Buccaneers'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Offense'), (SELECT positionID FROM positions WHERE position = 'QB')),
('8', 'Marcus', 'Mariota', '21', (SELECT teamID FROM teams WHERE mascot = 'Titans'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Offense'), (SELECT positionID FROM positions WHERE position = 'QB')),
('5', 'Blake', 'Bortles', '23', (SELECT teamID FROM teams WHERE mascot = 'Jaguars'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Offense'), (SELECT positionID FROM positions WHERE position = 'QB')),
('4', 'Derek', 'Carr', '24', (SELECT teamID FROM teams WHERE mascot = 'Raiders'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Offense'), (SELECT positionID FROM positions WHERE position = 'QB')),
('12', 'Andrew', 'Luck', '25', (SELECT teamID FROM teams WHERE mascot = 'Bills'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Offense'), (SELECT positionID FROM positions WHERE position = 'QB')),
('31', 'David', 'Johnson', '25', (SELECT teamID FROM teams WHERE mascot = 'Cardinals'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Offense'), (SELECT positionID FROM positions WHERE position = 'RB')),
('26', 'Le\'Veon', 'Bell', '25', (SELECT teamID FROM teams WHERE mascot = 'Steelers'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Offense'), (SELECT positionID FROM positions WHERE position = 'RB')),
('21', 'Ezekiel', 'Elliott', '22', (SELECT teamID FROM teams WHERE mascot = 'Cowboys'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Offense'), (SELECT positionID FROM positions WHERE position = 'RB')),
('25', 'LeSean', 'McCoy', '29', (SELECT teamID FROM teams WHERE mascot = 'Bills'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Offense'), (SELECT positionID FROM positions WHERE position = 'RB')),
('24', 'Jordan', 'Howard', '22', (SELECT teamID FROM teams WHERE mascot = 'Bears'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Offense'), (SELECT positionID FROM positions WHERE position = 'RB')),
('24', 'Devonta', 'Freeman', '25', (SELECT teamID FROM teams WHERE mascot = 'Falcons'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Offense'), (SELECT positionID FROM positions WHERE position = 'RB')),
('28', 'Melvin', 'Gordon', '24', (SELECT teamID FROM teams WHERE mascot = 'Chargers'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Offense'), (SELECT positionID FROM positions WHERE position = 'RB')),
('84', 'Antonio', 'Brown', '29', (SELECT teamID FROM teams WHERE mascot = 'Steelers'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Offense'), (SELECT positionID FROM positions WHERE position = 'WR')),
('13', 'Odell', 'Beckham Jr', '24', (SELECT teamID FROM teams WHERE mascot = 'Giants'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Offense'), (SELECT positionID FROM positions WHERE position = 'WR')),
('11', 'Julio', 'Jones', '28', (SELECT teamID FROM teams WHERE mascot = 'Falcons'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Offense'), (SELECT positionID FROM positions WHERE position = 'WR')),
('87', 'Jordy', 'Nelson', '32', (SELECT teamID FROM teams WHERE mascot = 'Packers'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Offense'), (SELECT positionID FROM positions WHERE position = 'WR')),
('13', 'Mike', 'Evans', '23', (SELECT teamID FROM teams WHERE mascot = 'Buccaneers'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Offense'), (SELECT positionID FROM positions WHERE position = 'WR')),
('13', 'Michael', 'Thomas', '23', (SELECT teamID FROM teams WHERE mascot = 'Saints'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Offense'), (SELECT positionID FROM positions WHERE position = 'WR')),
('18', 'AJ', 'Green', '29', (SELECT teamID FROM teams WHERE mascot = 'Bengals'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Offense'), (SELECT positionID FROM positions WHERE position = 'WR')),

-- Defense
('21', 'Landon', 'Collins', '24', (SELECT teamID FROM teams WHERE mascot = 'Giants'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Defense'), (SELECT positionID FROM positions WHERE position = 'DB')),
('20', 'Reshad', 'Jones', '29', (SELECT teamID FROM teams WHERE mascot = 'Dolphins'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Defense'), (SELECT positionID FROM positions WHERE position = 'DB')),
('22', 'Harrison', 'Smith', '28', (SELECT teamID FROM teams WHERE mascot = 'Vikings'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Defense'), (SELECT positionID FROM positions WHERE position = 'DB')),
('22', 'Keanu', 'Neal', '22', (SELECT teamID FROM teams WHERE mascot = 'Falcons'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Defense'), (SELECT positionID FROM positions WHERE position = 'DB')),
('33', 'Jamal', 'Adams', '21', (SELECT teamID FROM teams WHERE mascot = 'Jets'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Defense'), (SELECT positionID FROM positions WHERE position = 'DB')),
('37', 'John', 'Cyprien', '27', (SELECT teamID FROM teams WHERE mascot = 'Titans'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Defense'), (SELECT positionID FROM positions WHERE position = 'DB')),
('20', 'Kurt', 'Coleman', '29', (SELECT teamID FROM teams WHERE mascot = 'Panthers'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Defense'), (SELECT positionID FROM positions WHERE position = 'DB')),
('50', 'Telvin', 'Smith', '26', (SELECT teamID FROM teams WHERE mascot = 'Jaguars'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Defense'), (SELECT positionID FROM positions WHERE position = 'LB')),
('59', 'Luke', 'Kuechly', '26', (SELECT teamID FROM teams WHERE mascot = 'Panthers'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Defense'), (SELECT positionID FROM positions WHERE position = 'LB')),
('52', 'Alec', 'Ogletree', '26', (SELECT teamID FROM teams WHERE mascot = 'Rams'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Defense'), (SELECT positionID FROM positions WHERE position = 'LB')),
('58', 'Kwon', 'Alexander', '22', (SELECT teamID FROM teams WHERE mascot = 'Buccaneers'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Defense'), (SELECT positionID FROM positions WHERE position = 'LB')),
('54', 'Bobby', 'Wagner', '27', (SELECT teamID FROM teams WHERE mascot = 'Seahawks'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Defense'), (SELECT positionID FROM positions WHERE position = 'LB')),
('45', 'Deion', 'Jones', '22', (SELECT teamID FROM teams WHERE mascot = 'Falcons'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Defense'), (SELECT positionID FROM positions WHERE position = 'LB')),
('57', 'CJ', 'Mosley', '25', (SELECT teamID FROM teams WHERE mascot = 'Ravens'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Defense'), (SELECT positionID FROM positions WHERE position = 'LB')),
('99', 'JJ', 'Watt', '28', (SELECT teamID FROM teams WHERE mascot = 'Texans'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Defense'), (SELECT positionID FROM positions WHERE position = 'DE')),
('99', 'Joey', 'Bosa', '22', (SELECT teamID FROM teams WHERE mascot = 'Chargers'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Defense'), (SELECT positionID FROM positions WHERE position = 'DE')),
('94', 'Danielle', 'Hunter', '22', (SELECT teamID FROM teams WHERE mascot = 'Vikings'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Defense'), (SELECT positionID FROM positions WHERE position = 'DE')),
('54', 'Olivier', 'Vernon', '26', (SELECT teamID FROM teams WHERE mascot = 'Giants'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Defense'), (SELECT positionID FROM positions WHERE position = 'DE')),
('54', 'Melvin', 'Ingram', '28', (SELECT teamID FROM teams WHERE mascot = 'Chargers'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Defense'), (SELECT positionID FROM positions WHERE position = 'DE')),
('96', 'Muhammad', 'Wilkerson', '27', (SELECT teamID FROM teams WHERE mascot = 'Jets'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Defense'), (SELECT positionID FROM positions WHERE position = 'DE')),
('93', 'Calais', 'Campbell', '30', (SELECT teamID FROM teams WHERE mascot = 'Jaguars'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Defense'), (SELECT positionID FROM positions WHERE position = 'DE')),

-- Special Teams
('2', 'Matt', 'Bryant', '42', (SELECT teamID FROM teams WHERE mascot = 'Falcons'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Special Teams'), (SELECT positionID FROM positions WHERE position = 'K')),
('3', 'Stephen', 'Gostkowski', '33', (SELECT teamID FROM teams WHERE mascot = 'Patriots'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Special Teams'), (SELECT positionID FROM positions WHERE position = 'K')),
('3', 'Will', 'Lutz', '23', (SELECT teamID FROM teams WHERE mascot = 'Saints'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Special Teams'), (SELECT positionID FROM positions WHERE position = 'K')),
('9', 'Justin', 'Tucker', '27', (SELECT teamID FROM teams WHERE mascot = 'Ravens'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Special Teams'), (SELECT positionID FROM positions WHERE position = 'K')),
('3', 'Blair', 'Walsh', '27', (SELECT teamID FROM teams WHERE mascot = 'Seahawks'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Special Teams'), (SELECT positionID FROM positions WHERE position = 'K')),
('6', 'Caleb', 'Sturgis', '27', (SELECT teamID FROM teams WHERE mascot = 'Eagles'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Special Teams'), (SELECT positionID FROM positions WHERE position = 'K')),
('5', 'Dan', 'Bailey', '29', (SELECT teamID FROM teams WHERE mascot = 'Cowboys'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Special Teams'), (SELECT positionID FROM positions WHERE position = 'K')),
('6', 'Johnny', 'Hekker', '27', (SELECT teamID FROM teams WHERE mascot = 'Rams'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Special Teams'), (SELECT positionID FROM positions WHERE position = 'P')),
('5', 'Bradley', 'Pinion', '23', (SELECT teamID FROM teams WHERE mascot = '49ers'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Special Teams'), (SELECT positionID FROM positions WHERE position = 'P')),
('9', 'Brad', 'Wing', '26', (SELECT teamID FROM teams WHERE mascot = 'Falcons'), (SELECT positionGroupID FROM positionGroup WHERE positionGroup = 'Special Teams'), (SELECT positionID FROM positions WHERE position = 'P'));
