-- File that adds the teams using the correct SQL Syntax
-- INSERT INTO `teams`(`city`, `mascot`, `stadium`) VALUES ([value-1],[value-2],[value-3])
INSERT INTO `teams`(`city`, `mascot`, `stadium`) VALUES
('Arizona','Cardinals','University of Phoenix Stadium'),
('Chicago','Bears','Soldier Field'),
('Green Bay', 'Packers', 'Lambeau Field'),
('New York', 'Giants', 'MetLife Stadium'),
('Detroit', 'Lions', 'Ford Field'),
('Washington', 'Redskins', 'FedEx Field'),
('Philadephia', 'Eagles', 'Lincoln Financial Field'),
('Pittsburgh', 'Steelers', 'Heinz Field'),
('Los Angeles', 'Rams', 'Los Angeles Memorial Coliseum'),
('San Fransisco', '49ers', 'Levi\'s Stadium'),
('Cleveland', 'Browns', 'FirstEnergy Stadium'),
('Indianapolis', 'Colts', 'Lucas Oil Stadium'),
('Dallas', 'Cowboys', 'AT&T Stadium'),
('Kansas City', 'Cheifs', 'Arrowhead Stadium'),
('Los Angeles', 'Chargers', 'StubHub Center'),
('Denver', 'Broncos', 'Sports Authority Field at Mile High'),
('New York', 'Jets', 'MetLife Stadium'),
('New England', 'Patriots', 'Gillette Stadium'),
('Oakland', 'Raiders', 'Oakland–Alameda County Coliseum'),
('Tennessee', 'Titans', 'Nissan Stadium'),
('Buffalo', 'Bills', 'New Era Field'),
('Minnesota', 'Vikings', 'US Bank Stadium'),
('Atlanta', 'Falcons', 'Mercedes-Benz Stadium'),
('Miami', 'Dolphins', 'Hard Rock Stadium'),
('New Orleans', 'Saints', 'Mercedes-Benz Superdome'),
('Cincinnati', 'Bengals', 'Paul Brown Stadium'),
('Seattle', 'Seahawks', 'Century Link Field'),
('Tampa Bay', 'Buccaneers', 'Raymond James Stadium'),
('Carolina', 'Panthers', 'Bank of America Stadium'),
('Jacksonville', 'Jaguars', 'EverBank Field'),
('Baltimore', 'Ravens', 'M&T Bank Stadium'),
('Houston', 'Texans', 'NRG Stadium');
